### PR TITLE
Split home part into multiple editable parts

### PR DESCRIPTION
**Pull request by torlokken**

### CODE REVIEW

**Comment by torlokken** [comment]
Note that some of the very generic css needs to be refined to make it work better with editable content. I.e. global p styling.

**Comment by fecosnippets** [comment]
Thank you!
@ezchile that is more for you.
We will figure these out when we get there (doing other things atm)

**Comment by ezchile** [comment]
Hi @torlokken, 

When recreating the home page with the sections that you have kindly created, how do we export them, so that for instance Frank (@fecosnippets) can see the changes that I'm making (adding data to ul / li's etc.)

**Comment by torlokken** [comment]
Hi, you can use this app on Enonic Market for data import/export: https://market.enonic.com/vendors/glenn-ricaud/systems.rcd.enonic.datatoolbox 

Or alternatively you can use the Toolbox CLI in Enonic XP: http://xp.readthedocs.io/en/stable/operations/export.html?highlight=export

**Comment by ezchile** [comment]
Hi @torlokken,

I've noticed that you've commented out the embedded youtube video iFrame in fp-what-is.html, which seems to cause an error when uncommented. Is there a way around that?

Also, some H1's contain a span for screen-reader specific extra text, is that possible in EnonicXP?

Thanks for your help on this.

**Pull request merged**
